### X resources ###

# Load configuration from .Xresource
set_from_resource $foreground foreground #000000
set_from_resource $background background #000000
set_from_resource $black_0 color0 #000000
set_from_resource $black_1 color0 #000000
set_from_resource $red color1 #000000
set_from_resource $green color2 #000000
set_from_resource $yellow color3 #000000
set_from_resource $blue color4 #000000
set_from_resource $magenta color5 #000000
set_from_resource $cyan color6 #000000
set_from_resource $white color7 #000000

### Colors scheme ###
#133b5c #133b5c
# class                 border  bground text    indicator child_border
client.focused          #090B10 #090B10 #fabd2f #BF40BF   #285577
client.focused_inactive #090B10 #090B10 #FFFFFF #484E50   #5F676A
client.unfocused        #090B10 #090B10 #888888 #292D2E   #222222
client.urgent           #2F343A #900000 #FFFFFF #900000   #900000
client.placeholder      #000000 #0C0C0C #FFFFFF #000000
client.background 			#800080 #090B10 #090B10
