# Executions

# xss-lock grabs a logind suspend inhibit lock and will use i3lock to lock the
# screen before suspend.
# exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork
exec_always --no-startup-id $HOME/.config/polybar/launch.sh
exec --no-startup-id nitrogen --restore
exec --no-startup-id dunst
exec --no-startup-id discord
exec --no-startup-id slack 

# Workspaces applications

exec --no-startup-id i3-msg "workspace 1; exec ${TERMINAL:-alacritty} -e ~/.local/bin/welcome.sh"
# exec --no-startup-id i3-msg 'workspace 1: term; exec alacritty'
# exec --no-startup-id i3-msg 'workspace 2: coding; exec alacritty'
