### i3-gaps  ###

# Necessary for i3-gaps to work properly (pixel can be any value)

# Smart Gaps
smart_gaps on

# Smart Borders
smart_borders on 

# Set inner/outer gaps
gaps inner 0px
gaps outer 0px
