# Mode

# Terminals

# bindsym $mod+Shift+x mode "$terminals"
# set $terminals Launch: [a]alacritty [u]urxvt [x]xterm
# mode "$terminals" {
#   bindsym a exec alacritty; exec --no-startup-id xdotool key "Escape"
#   bindsym u exec urxvt; exec --no-startup-id xdotool key "Escape"
#   bindsym x exec xterm; exec --no-startup-id xdotool key "Escape"
#   bindsym Return mode "default"
#   bindsym Escape mode "default"
# }

# Editors

# bindsym $mod+e mode "$editors"
# set $editors Launch: [c]vscode [n]nvim [v]vim 
# mode "$editors" {
#   bindsym c exec code; exec --no-startup-id xdotool key "Escape"
#   bindsym v exec alacritty -e vim; exec --no-startup-id xdotool key "Escape"
#   bindsym n exec alacritty -e nvim; exec --no-startup-id xdotool key "Escape"
#   bindsym Return mode "default"
#   bindsym Escape mode "default"
# }

# Browsers

# bindsym $mod+b mode "$browsers"
# set $browsers Launch: [c]chromium [f]firefox [q]qutebrowser [s]surf
# mode "$browsers" {
#   bindsym c exec google-chrome;  exec --no-startup-id xdotool key "Escape"
#   bindsym f exec firefox;  exec --no-startup-id xdotool key "Escape"
#   bindsym e exec edge;  exec --no-startup-id xdotool key "Escape"
#   bindsym q exec qutebrowser;  exec --no-startup-id xdotool key "Escape"
#   bindsym s exec surf https://www.google.com; exec --no-startup-id xdotool key "Escape"
#   bindsym Return mode "default"
#   bindsym Escape mode "default"
# }

# Window resizing

# bindsym $mod+r mode "resize"
# mode "resize" {
#   bindsym h resize shrink width 10 px or 10 ppt
#   bindsym j resize shrink height 10 px or 10 ppt
#   bindsym k resize grow height 10 px or 10 ppt
#   bindsym l resize grow width 10 px or 10 ppt
# 
#   bindsym Left resize shrink width 5 px or 5 ppt
#   bindsym Down resize grow height 5 px or 5 ppt
#   bindsym Up resize shrink height 5 px or 5 ppt
#   bindsym Right resize grow width 5 px or 5 ppt
# 
#   # back to normal: Enter or Escape or $mod+r
#   bindsym Return mode "default"
#   bindsym Escape mode "default"
#   bindsym $mod+r mode "default"
# }


