title_align  center
default_border pixel 3

floating_minimum_size 120 x 50
floating_maximum_size -1 x -1

for_window [title="command-palette"] floating enable
# for_window [title="Alacritty"] floating enable
for_window [title="video0 - mpv"] floating enable
for_window [title="video0 - mpv"] sticky enable
for_window [title="video0 - mpv"] border pixel 0
no_focus [title="video0 - mpv"]

font pango:Iosevka Nerd Font 11

for_window [class=".*"] title_format %title
for_window [class="Pcmanfm"] floating enable
for_window [class="xterm"] title_format %title %class %instance

for_window [class="i3-frame"] title_format '%title (%id)'
for_window [class=…] focus parent, [] title_format …, focus child

# 
for_window [class="Alacritty"] title_format %title %class %instance, floating enable, resize set 1200 600, move position center
for_window [class="XTerm"] title_format %title %class %instance, floating enable, resize set 1200 600, move position center
for_window [class="Zutty"] floating enable, resize set 1200 600

# 
for_window [class="Pcmanfm"] floating enable, resize set 1200 600
for_window [class="Nemo"] floating enable, resize set 1200 600


for_window [class="vlc"] floating enable, resize set 1200 600
for_window [class="Nitrogen"] floating enable, resize set 800 420

#
for_window [class="Transmission-gtk"] floating enable, resize set 800 420

# Widgets
for_window [class="Blueman-manager"] floating enable, resize set 800 420
for_window [class="gnome-disk-image-mounter"] floating enable, resize set 800 420


