# ~/.config/i3/workspaces.conf
# i3 Workspaces and monitors configuration



# Assigning workspaces to monitors
set $ws1 "1: term"
set $ws2 "2: coding"
set $ws3 "3: web"
set $ws4 "4: documents"
set $ws5 "5: mail"
set $ws6 "6: calendar"
set $ws7 "7: tasks"
set $ws8 "8: infra"
set $ws9 "9: medias"
set $ws10 "10: gfx"


